### ISSUE TITLE
Make mass biome replacement easier

### ISSUE THREAD

**Issue by ModDehBird** [WerDei/Biome-Replacer#11]
How it works currently if you want to turn ALL biomes into just a few, you have to make a big list of all the biomes.

Im looking to replace all the biomes with just a few but itd take a while if you add in all the biomes mods. just being able to set all of them to nothing or a singular biome then start on more fine tuning would be nice.

**Comment by WerDei** [comment]
I'm not actively developing this mod at the moment, so no promises here. But, just in case someone else (or me in the future) wants to work on this - the simplest way would be supporting [biome tags](https://minecraft.wiki/w/Tag#Biome_tags) in config. This way, for example, you could use `#minecraft:is_forest > minecraft:desert` to turn every forest into a desert.
