### ISSUE TITLE
Rules not applying in Client on world load

### ISSUE THREAD

**Issue by Etos2** [WerDei/Biome-Replacer#12]
Loading an existing world in the client does not continue to apply replacement rules.
From investigatng, it seems that `BiomeReplacer.prepareReplacementRules` is called _after_ `findAndReplace` within the `MultiNoiseBiomeSource` mixin (which makes no sense to me). This means that `modifiedParameters` is null and no rules are applied during world load.

This thankfully does not occur on a dedicated server, but is still quite problematic. Unfortunately I'm too new to modding to guarantee `BiomeReplacer.prepareReplacementRules` is called as early as possible.

Here is a snippet of the logs on world load:
> [19:01:25] [Render thread/INFO]: [BiomeReplacer] No rules found, not replacing anything
> [19:01:25] [Render thread/INFO]: [BiomeReplacer] No rules found, not replacing anything
> [19:01:25] [Render thread/INFO]: [BiomeReplacer] Loaded 39 biome replacement rules

Compared to a snippet of logs on world creation:
> [19:07:56] [Render thread/INFO]: [BiomeReplacer] Loaded 39 biome replacement rules
> [19:07:56] [Server thread/INFO]: [BiomeReplacer] Biomes replaced successfully
> [19:07:58] [Server thread/INFO]: [BiomeReplacer] Biomes replaced successfully

To replicate:
1. Install Biome-Replacer and Fabric-API
2. Create a new singleplayer world in the client
3. Biomes are successfully replaced
4. Exit, and load world again
5. Biomes are no longer replaced
I recommend low Render Distance for exploring new chunks.

For testing, I used the following config:
https://pastebin.com/jgLvatJg

**Comment by WerDei** [comment]
Damn, I encountered this bug and thought that it only applied to "re-create world" feature, but turns out it's way more severe. I'm not sure how to fix it at the moment, because I'm already calling `prepareReplacementRules` as early as I can, I think? I might need help from someone else who is more knowledgeable.

**Comment by Etos2** [comment]
I'm going to try and have a peek at what's different between the dedicated server and the client that would load it earlier some time in the future (migrating a server to 1.21 currently).
The only idea I can think of is somehow hooking into the registry used by `prepareReplacementRules` to get it asap or go deeper and replace biomes as they are initialised.
I also initially experimented with using the `Server_Starting` event instead of a mixin but that is always too late, so the solution will probably be a mixin.
This is probably an issue to bring up in the Fabric discord though, they're a smart bunch.

**Comment by CA117M** [comment]
anyone else getting network protocol errors in singleplayer when using the load-in-twice work around? I can replicate the error by attempting to load chunks that contain a biome I've listed to be replaced in worlds I have loaded into twice in the same instance of mc, closing the client and relaunching fixes the problem. Basically the work around doesn't work for me bc mc kicks me out for invalid internal-server data packets

**Comment by WerDei** [comment]
@CA117M Yeah, my "workaround" is only barely better than nothing. Even I had an issue with how it froze the game when closing it. I really, *really* should look more into the issue since it's shloudn't be too hard to fix in theory, just requires some fiddling around with Minecraft's code. Sorry, I don't have a good excuse for why it's taking me that long. ADHD is a bitch.

**Comment by WerDei** [comment]
I think I've found a good place to inject the `prepareReplacementRules` call, let me know if you have any isses with a new version -I'll upload it to usual places shortly. So far, I've only found a *very* small issue with how `/locate biome` command acts after using "Re-Create World". 

Again, I'm sorry it took so long for me to take a look! I'll try to be better about critical issues next time.

**Comment by CA117M** [comment]
OMG YOU DID IT YOU BLOODY LEGEND IT WORKS PERFECTLY FIRST TRY, I've been looking for a working mod that does this for years and HERE YOU ARE, AN HOUR LATER, MWAH YOU'RE THE BEST!!!!!!!!!!! :DDDDDD
