### ISSUE TITLE
Oceanize Attempt

### ISSUE THREAD

**Issue by Niconoko** [WerDei/Biome-Replacer#19]
![image](https://github.com/user-attachments/assets/6a7c4ce7-83f7-48da-b5b7-f0d46b3fba83)
Me tried to replace all normal biomes into ocean type biome, and... land still generated. (Mod v1.2, Forge v1.20.1-47.3.0)

**Comment by WerDei** [comment]
That's not possible to do with this mod, see #6 for explanation. I wish I could suggest you some tools or mods that can help create ocean worlds, but I'm not aware of any, unfortunately.

**Comment by Niconoko** [comment]
Welp, time to flood the world (´ - ω -｀)
