### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by PseudoSquared** [WerDei/Biome-Replacer#20]
I'm currently trying to use this mod on 1.20.1 on Forge, but it seems to be broken for the latest version of Forge.

**Comment by WerDei** [comment]
Sorry it's not working for you, but I'm unfortunately not interested in working on Forge versions at the moment. You might try asking @LegendarySpy - NeoForge fork maintainer - wether they want to take a look/create a new backport.

**Comment by LegendarySpy** [comment]
![Michael Scott Excited](https://media.tenor.com/2EOBvOkH_6AAAAAM/bird-calender.gif)

I've started working on 1.19.2 and 1.20.1 👀

**Comment by PseudoSquared** [comment]
That's amazing! Do you have a time frame out of curiosity?

**Comment by LegendarySpy** [comment]
I'll try to get a working basic demo by this weekend and maybe a full release a few days after

**Comment by PseudoSquared** [comment]
Lovely, thank you so much. Hope programming goes smoothing without too many bugs! Please let me know if/when you've finished the demo/release.

**Comment by PseudoSquared** [comment]
Just wanted to check in and see if you've made any progress. I'm not in a rush per say, I'm playing another modpack while I wait, but I'd just like to check in and see how you're doing and if it's worth waiting for.

**Comment by LegendarySpy** [comment]
Yeah, no worries, I rebuilt most of the mod and forgot that WerDei actually had a basic forge port existing, so hopefully by some point tomorrow it should be somewhat functioning. If you could, could you make an issue on the neoforge page, helps clean everything up, and hopefully WerDei's notifications as-well: [Neoforge Version](https://github.com/LegendarySpy/Biome-Replacer-Neoforge/issues)
