### ISSUE TITLE
Forge version?

### ISSUE THREAD

**Issue by V0idshock** [WerDei/Biome-Replacer#3]
I know the annoyance of people asking for the other version, but i think out of all mods to be ported, this one is actually useful.
So at least consider it, just for this simple-ish project :)

**Comment by WerDei** [comment]
Normally I wouldn't bother with Forge, but this mod is small enough that I might try it sometime. 
In the meantime, you can try using [Sinytra Connector](https://www.modrinth.com/mod/connector), or any other compat tool. Again, since this mod is small, it might just work without issues.

**Comment by KostromDan** [comment]
> Normally I wouldn't bother with Forge, but this mod is small enough that I might try it sometime. In the meantime, you can try using [Sinytra Connector](https://www.modrinth.com/mod/connector), or any other compat tool. Again, since this mod is small, it might just work without issues.

Hi, I'm creator of M-Tech modpack for 1.19.2. It has 1.2m downloads on curseforge.
I really need this mod.
Will you able to port it?

**Comment by WerDei** [comment]
Did a quick test today and got it working on forge 1.20.1. I did not look into 1.19.2 yet, but I think I can make it work.

**Comment by KostromDan** [comment]
Any chance you release it?

**Comment by WerDei** [comment]
My bad, I run into some troubles setting up the automatic publishing, put it off, and then completely forgot about it. Sorry about that!

Gonna publish it manually for now. Will look at backporting in a little bit, too.

**Comment by KostromDan** [comment]
Thanks! Really waiting 1.19.2 backport.

**Comment by KostromDan** [comment]
> My bad, I run into some troubles setting up the automatic publishing, put it off, and then completely forgot about it. Sorry about that!
> 
> Gonna publish it manually for now. Will look at backporting in a little bit, too.

Any chance 1.19.2 forge backport?
I really need this mod in next major modpack udpate which close to release.
