### ISSUE TITLE
[Feature Sugestion] Add replace chance

### ISSUE THREAD

**Issue by elhertz** [WerDei/Biome-Replacer#4]
I want to make modded biomes work with terralith using your mod, but sometimes you don't want to completely replace a biome, that's where a feature to add a chance variable would be useful

**Comment by WerDei** [comment]
While a great feature in theory, I don't think it's possible (or at least not easy) to implement. The way modern Minecraft generates biomes makes it hard to tell where an instance of a biome begins and ends, as far as I know.
