### ISSUE TITLE
crash when loading world with changed config

### ISSUE THREAD

**Issue by ninjomoe** [WerDei/Biome-Replacer#8]
i tried removing some of the terralith biomes. I cant create a world because it is permanently stuck on the loading screen.

[crash-2024-08-06_22.49.07-server.txt](https://github.com/user-attachments/files/16515646/crash-2024-08-06_22.49.07-server.txt)
[biome_replacer.txt](https://github.com/user-attachments/files/16515649/biome_replacer.txt)

**Comment by ninjomoe** [comment]
Just wanted to add, it doesnt even work with vanilla biomes. i tried just putting in: 
minecraft:dark_forest > minecraft:cherry_grove
and it still didnt load.

**Comment by LegendarySpy** [comment]
Are you currently using Terrablender with sinytra connector. If so Terrablender currently doesn't play nicely with Biome Replacer as mentioned in  #7

**Comment by ninjomoe** [comment]
Im not using Terrablender, but i am using Sinytra Connector for the Betterend mod. Also, i used the config on the server im hosting and it does work on there, so it has to be some kind of client mod.

**Comment by ninjomoe** [comment]
is the way i did my config even right? dont there have to be any commas in between or any other formating?
